import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaTruck } from "react-icons/fa";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className=" bg-white h-[100px] flex items-center justify-between ">
        <div className="ml-28">
          <Link className="flex gap-4 items-center"  href="/" > 
           {/* <FaTruck className="text-blue-500" size={60}  />  */}
          <h1  className="text-3xl  font-semibold">Expo</h1>

           </Link>
          </div> 
          <div className="mr-28 flex gap-4">
            <Button variant={'secondary'}>Login</Button>
            <Button>Get started</Button>
          </div>
      </div >
        {children}
      </body>
    </html>
  );
}
